# Generated by Django 3.0.3 on 2020-08-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='lorem_ipsum', max_length=4000),
            preserve_default=False,
        ),
    ]
