# Generated by Django 3.0.3 on 2020-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='Mafia', unique=True),
            preserve_default=False,
        ),
    ]
