# Generated by Django 3.0.3 on 2020-08-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_board_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
    ]
